image:
  file: .gitpod.Dockerfile

tasks:
  - init: 
  # Visual check that Azure CLI, Azure Functions Core Tools, and dotnet core are available 
  # then build and run Function which will open a web preview (see ports section below) on port 7071 when started
  - command: az --version && func --version && dotnet --list-sdks && cd /workspace/azure-sa-function-tests/LocalFunctionProj/ && func start --csharp

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 7071
    onOpen: open-browser
